name: check.yml
on: [ pull_request, push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libjq and oniguruma
        run: sudo apt-get update && sudo apt-get install -y libjq1 libjq-dev jq libonig-dev
      - name: Install clang
        run: sudo apt-get install -y clang
      - name: Set JQ_LIB_DIR
        run: echo "JQ_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
      - name: Use clang for C/C++ compilation
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose